export const ROLES = { ADMIN: 'ADMIN', WAITER: 'WAITER', KITCHEN: 'KITCHEN', CASHIER: 'CASHIER' };
export const ORDER_STATUS = ['CHO_XAC_NHAN', 'DANG_CHE_BIEN', 'SAN_SANG_PHUC_VU', 'DA_THANH_TOAN', 'DA_HUY'];
export const ITEM_STATUS = ['CHO_BEP', 'DANG_NAU', 'HOAN_THANH'];
